language: cpp

install:
  - sudo apt-get install -y cmake
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest
  - sudo mkdir build
  - cd build
  - sudo cmake ..
  - sudo make
  - sudo cp libgtest* /usr/lib/

before-script: cmake .

script:
  - make
  - ./ts_travis_gtest
